package com.timetabling.server.data.entities.tt;

import java.util.List;

import com.timetabling.server.data.entities.curriculum.Specialty;
import com.timetabling.server.generating.Markable;

public class GroupTT implements Markable {
	
	/** {@link #groupName} should be generated by {@link Specialty#getShortName()}, year and {@link #groupNumber} <br>*/
	private String groupName;
	private byte groupNumber;
	private List<Lesson> lessons;
	
	public GroupTT() {
	}
	
	public String getGroupName() {
		return groupName;
	}

	/** {@link #groupName} should be generated by {@link Specialty#getShortName()}, year and {@link #groupNumber}*/
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}
	
	public byte getGroupNumber() {
		return groupNumber;
	}
	
	public void setGroupNumber(byte groupNumber) {
		this.groupNumber = groupNumber;
	}
	
	public List<Lesson> getLessons() {
		return lessons;
	}
	
	public double getMarkForVersion(Version version) {
		// TODO
		return 1d;
	}
	
}
